default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: utf8
  username: postgres
  host: localhost

development:
  <<: *default
  database: test_task

test:
  <<: *default
  database: test_task_test

production:
  <<: *default
  database: test_task_production
